                             Assignment 2 Digit Recognition using KNN Classifier

In [2]:
#standard python imports to perform KNN

from sklearn import datasets
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import numpy as np
from sklearn.metrics import confusion_matrix
import math
import collections as col


In [3]:
# Loading digits data set

digits = datasets.load_digits()

n_samples = len(digits.images)

print(n_samples)

#size of each digit is 8*8 pixel.

print(digits.images.shape)


1797
(1797, 8, 8)


In [12]:
#Dividing data

data, target = digits.data , digits.target

print("arrays of digits will be\n",digits.data)

print("Target will be\n", digits.target)

data = digits.images.reshape((n_samples,-1))

#After falttening the image 

print("flattened data will be:\n",digits.data)

print("target will be:\n", digits.target)

print("flattend shape of entire data will be\n", data.shape)
oad a dataset and spit into train and test sets in PythonPython
import csv
import random
def loadDataset(filename, split, trainingSet=[] , testSet=[]):

	    lines = csv.reader(csvfile)
	    dataset = list(lines)
	    for x in range(len(dataset)-1):
	        for y in range(4):
	            dataset[x][y] = float(dataset[x][y])
	        if random.random() < split:
	            trainingSet.append(dataset[x])
	        else:
	            testSet.append(datase
import csv
import random
def loadDataset(filename, split, trainingSet=[] , testSet=[]):
	with open(filename, 'rb') as csvfile:
	    lines = csv.reader(csvfile)
	    dataset = list(lines)
	    for x in range(len(dataset)-1):
	        for y in range(4):
	            dataset[x][y] = float(dataset[x][y])
	        if random.random() < split:
	            trainingSet.append(dataset[x])
	        else:
	            testSet.append(dataset[x])







arrays of digits will be
 [[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]
Target will be
 [0 1 2 ... 8 9 8]
flattened data will be:
 [[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]
target will be:
 [0 1 2 ... 8 9 8]
flattend shape of entire data will be
 (1797, 64)


In [5]:
#splitting data into 50:50 ratio

X_train,X_test,y_train,y_test = train_test_split(data, target, test_size = 0.5,random_state = 42)

print(len(X_train), len(y_train), len(X_test))

print(X_train[1])
print(y_train[1])
print(X_test[1])
print(y_test[1])

898 898 899
[ 0.  0.  9. 16. 16.  7.  0.  0.  0.  2. 16. 11.  4. 15.  2.  0.  0.  4.
 16.  2.  2. 16.  6.  0.  0.  0. 13. 11. 13. 16. 10.  0.  0.  0.  1. 10.
 13. 16.  6.  0.  0.  0.  0.  0.  3. 16.  7.  0.  0.  0.  0.  2. 13. 14.
  1.  0.  0.  0. 11. 15. 15.  6.  0.  0.]
9
[ 0.  0. 11. 16.  8.  0.  0.  0.  0.  6. 16. 11. 13.  9.  0.  0.  0.  7.
 16.  0.  9. 16.  0.  0.  0.  2. 15. 12. 16. 16.  3.  0.  0.  0.  5.  7.
  7. 16.  4.  0.  0.  0.  0.  0.  5. 16.  5.  0.  0.  0.  3.  7. 16. 11.
  0.  0.  0.  0. 13. 16. 11.  1.  0.  0.]
9


In [14]:
def predict(X_train, y_train, X_test, k):
    distance = []
    targets  = []
    for i in range(len(X_test-1)):
        for j in range(len(X_train)):
        distance.append([np.sqrt(np.sum(np.square(X_test[i,:] - X_train[j,:]))),i])
    distance = sorted(distance)
    for i in range(k):
        index = distance[i][1]
        targets.append(y_train[index])
    return targets
    

IndentationError: expected an indented block (<ipython-input-14-5abdcf57b70a>, line 6)

In [7]:
#a = predict(X_train, y_train, X_test,4)

In [8]:
def KNEAR(X_train, y_train, X_test, k):
    predictions = []
    for i in range(len(X_test)):
        predictions.append(predict(X_train, y_train, X_test[i,:], k))
    return np.asarray(predictions)
predictions = KNEAR(X_train, y_train, X_test, 50)
print(len(predictions))
print(len(y_test))

899
899


In [9]:
def getAccuracy(y_test, predictions):
    correct = 0
    for x in range(len(y_test)):
        if y_test[x] is predictions[x]:
            corect +=1
    return (correct/float(len(y_test))) * 100.0
accuaracy = getAccuracy(y_test, predictions)
print(accuaracy)

0.0
